install.packages("tidyverse")
install.packages("knitr")
install.packages("rmarkdown")
install.packages("git2r")
install.packages("devtools")
install.packages("remotes")
remotes::install_github("benmarwick/rrtools")
